[project]
name = "SlyAPI"
version = "0.1.2"
description = "No-boilerplate, async and typed Twitter access."
readme = "README.md"
requires-python = ">=3.10"
license = { file="LICENSE" }
authors = [{name="Dunkyl 🔣🔣"}]
classifiers = [
    "Operating System :: OS Independent"
]
dependencies = [
    'SlyAPI >= 0.2.4',
    'aiofiles',
]
[project.optional-dependencies]
dev = [
    'pytest',
    'pytest-asyncio'
]

[project.urls]
Homepage = "https://docs.dunkyl.net/SlyTwitter-Python/"
Repository = "https://github.com/dunkyl/SlyTwitter-Python"
Documentation = "https://docs.dunkyl.net/SlyTwitter-Python/"
"Bug Tracker" = "https://github.com/dunkyl/SlyTwitter-Python/issues"

[build-system]
requires = ["setuptools", "wheel"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["test"]